title: "Parham Pishro"
description: "Data Scientist"
url: "https://parhampishro.github.io"
baseurl: ""

# Author
author:
  name: "Parham Pishro"
  bio: "Data Scientist"
  location: "Iran"
  email: "PrPishro@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/parhampishro"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/parham-pishro"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:PrPishro@gmail.com"

# Theme and Settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"
locale: "en-US"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# SASS Settings
sass:
  sass_dir: _sass
  style: compressed

# Pagination Settings
paginate: 6
paginate_path: "/blog/page:num/"

# Search Settings  
search: true
search_full_content: true

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
